### ISSUE TITLE
Return value of "SmartyGettext\Console\Command\Extract::execute()" must be of the type int, "null" returned

### ISSUE THREAD

**Issue by kumy** [smarty-gettext/tsmarty2c#18]
I just upgraded my project and now getting this error:
```
Process ./website/app-templates/foundation-emails/dist/index.html
Done
PHP Fatal error:  Uncaught TypeError: Return value of "SmartyGettext\Console\Command\Extract::execute()" must be of the type int, "null" returned. in /home/kumy/GIT/geokrety-website_new-theme/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 ./vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run()
#1 ./vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#2 ./vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#3 ./vendor/smarty-gettext/tsmarty2c/bin/tsmarty2c.php(50): Symfony\Component\Console\Application->run()
#4 {main}
  thrown in ./vendor/symfony/console/Command/Command.php on line 261
```

Since commit https://github.com/symfony/console/commit/cdef5a4a0d8045299adf0a52a625606cb5c3bd5b `Command::execute()` must return an `int`
```
Changelog entry:
 * deprecated returning `null` from `Command::execute()`, return `0` instead
```

The actual code return `void`
https://github.com/smarty-gettext/tsmarty2c/blob/4193d1442e35b40d33cc8ca03cbf0285dd177210/src/Console/Command/Extract.php#L58-L94

My relevant versions:
```
smarty-gettext/tsmarty2c             0.2.0
symfony/console                      v5.1.8
```

**Comment by kumy** [comment]
@glensc Please fin PR #19
